export const products = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    description: "Latest iPhone with advanced camera system",
    price: 79999,
    category: "smartphones",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 25,
    low_stock_threshold: 5,
  },
  {
    id: 2,
    name: "Samsung Galaxy S24",
    description: "Flagship Android smartphone with AI features",
    price: 69999,
    category: "smartphones",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 3,
    low_stock_threshold: 5,
  },
  {
    id: 3,
    name: "Google Pixel 8 Pro",
    description: "Pure Android experience with top-notch camera",
    price: 74999,
    category: "smartphones",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 12,
    low_stock_threshold: 5,
  },
  {
    id: 4,
    name: "Apple MacBook Pro 16",
    description: "Powerful laptop for professionals",
    price: 189999,
    category: "laptops",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 8,
    low_stock_threshold: 3,
  },
  {
    id: 5,
    name: "Dell XPS 15",
    description: "Sleek and powerful Windows laptop",
    price: 159999,
    category: "laptops",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 2,
    low_stock_threshold: 3,
  },
  {
    id: 6,
    name: "LG OLED C3",
    description: "Stunning OLED TV with vibrant colors",
    price: 129999,
    category: "televisions",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 15,
    low_stock_threshold: 4,
  },
  {
    id: 7,
    name: "Sony Bravia XR",
    description: "Premium LED TV with excellent picture quality",
    price: 109999,
    category: "televisions",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 4,
    low_stock_threshold: 4,
  },
  {
    id: 8,
    name: "Apple Watch Series 9",
    description: "Advanced smartwatch with health tracking",
    price: 39999,
    category: "wearables",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 30,
    low_stock_threshold: 6,
  },
  {
    id: 9,
    name: "Samsung Galaxy Watch 6",
    description: "Stylish smartwatch with fitness features",
    price: 34999,
    category: "wearables",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 1,
    low_stock_threshold: 6,
  },
  {
    id: 10,
    name: "Airpods Pro 2",
    description: "Premium wireless earbuds with noise cancellation",
    price: 24999,
    category: "audio",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 18,
    low_stock_threshold: 5,
  },
  {
    id: 11,
    name: "Sony WH-1000XM5",
    description: "Industry-leading noise-canceling headphones",
    price: 29999,
    category: "audio",
    image: "/placeholder.svg?height=300&width=300",
    stock_quantity: 7,
    low_stock_threshold: 5,
  },
]
